# Generated by Django 3.2.25 on 2025-07-21 16:47

from django.db import migrations, models
import voitures.models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='idVoiture',
            field=models.CharField(default=voitures.models.generate_custom_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
