# Generated by Django 3.2.25 on 2025-07-27 19:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import factures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('idFacture', models.CharField(default=factures.models.generate_facture_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('date_voyage', models.DateField()),
                ('date_retour', models.DateField()),
                ('date_facture', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('payé', 'Payé'), ('en_attente', 'En attente'), ('annulé', 'Annulé')], default='en_attente', max_length=50)),
                ('montants', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'db_table': 'factures',
            },
        ),
    ]
