# Generated by Django 3.2.25 on 2025-07-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='id_client',
            new_name='clientId',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='date_facture',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='date_retour',
            new_name='dateReturn',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='date_voyage',
            new_name='dateTravel',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='montants',
            new_name='totalPrice',
        ),
    ]
