# Generated by Django 3.2.25 on 2025-07-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('nbpersonnes', models.PositiveIntegerField()),
                ('destinations', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
