# Generated by Django 3.2.25 on 2025-07-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20250717_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lastVisit',
            field=models.DateField(auto_now=True),
        ),
    ]
