# Generated by Django 3.2.25 on 2025-07-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('idHebergement', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('priceRange', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('amenities', models.JSONField()),
                ('capacity', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('favorite', models.BooleanField(default=False)),
                ('lastUsed', models.DateField()),
                ('popularity', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'hebergements',
            },
        ),
    ]
