# Generated by Django 3.2.25 on 2025-07-17 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hebergements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hebergement',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hebergement',
            name='lastUsed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
