# Generated by Django 3.2.25 on 2025-07-18 06:19

from django.db import migrations, models
import hebergements.models


class Migration(migrations.Migration):

    dependencies = [
        ('hebergements', '0002_auto_20250717_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebergement',
            name='idHebergement',
            field=models.CharField(default=hebergements.models.generate_custom_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
