# Generated by Django 3.2.25 on 2025-07-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='title',
            new_name='titles',
        ),
    ]
